blank_issues_enabled: false
contact_links:
  - name: 📝 User Support
    url: https://discuss.doomemacs.org/new?category=questions
    about: "Ask the community for help"
  - name: 📣 Announcements
    url: https://discuss.doomemacs.org/categories/announcements
    about: "Follow project news, releases, and announcements"
  - name: Official Documentation
    url: https://docs.doomemacs.org
    about: "Also available from within Doom: `M-x doom/help`"
  # - name: Community Wiki
  #   url: https://wiki.doomemacs.org
  #   about: "The Community-maintained wiki"
  # - name: Frequently asked questions
  #   url: https://docs.doomemacs.org/latest/faq
  #   about: "Answers to common questions and solutions for frequently brought up issues"
  - name: Do-not-PR list
    url: https://doomemacs.org/donotpr
    about: "A list of pull requests that won't be accepted"
  - name: Visit our Discussions board
    url: https://discuss.doomemacs.org
    about: "Our public discussion and user support forum"
  - name: Visit our Discord
    url: https://discord.doomemacs.org
    about: "A less formal space to chat, get to know the community, and get help quick"
