blank_issues_enabled: false
contact_links:
  - name: Official documentation
    url: https://docs.doomemacs.org
    about: "Our official manual on how to use, abuse, and confuse Doom Emacs"
  - name: Frequently asked questions
    url: https://docs.doomemacs.org/latest/faq
    about: "Answers to common questions and solutions for frequently brought up issues"
  - name: Do-not-PR list
    url: https://discourse.doomemacs.org/do-not-pr
    about: "A list of pull requests that won't be accepted"
  - name: Visit our Discourse
    url: https://discourse.doomemacs.org
    about: "Our public discussion and support forum; includes guides, news, and resources"
  - name: Visit our Discord
    url: https://doomemacs.org/discord
    about: "A less formal space to chat, get to know the community, and get help quick"
