blank_issues_enabled: false
contact_links:
  - name: Official documentation
    url: https://docs.doomemacs.org
    about: "Our official manual on how to use, abuse, and confuse Doom Emacs"
  - name: Frequently asked questions
    url: https://docs.doomemacs.org/latest/faq
    about: "Answers to common questions and solutions for frequently brought up issues"
  - name: 3rd-party learning resources
    url: https://discourse.doomemacs.org/resources
    about: "A curated collection of non-official resources to help you learn Emacs and Doom"
  - name: Visit our website
    url: https://doomemacs.org
    about: "Our public discussion and support forum, as well as our public knowledge base"
  - name: Visit our Discourse
    url: https://discourse.doomemacs.org
    about: "Our public discussion and support forum, as well as our public knowledge base"
  - name: Visit our Discord
    url: https://doomemacs.org/discord
    about: "A less formal space to chat, get to know the community, and get help quick"
