blank_issues_enabled: false
contact_links:
  - name: Do-not-PR list
    url: https://doomemacs.org/donotpr
    about: "A list of pull requests that won't be accepted"
  - name: Visit our Discussions board
    url: https://doomemacs.org/discuss
    about: "Our public discussion and support forum"
  - name: Visit our Discord
    url: https://doomemacs.org/discord
    about: "A less formal space to chat, get to know the community, and get help quick"
