---
name: 📝 Feature request
description: Propose a new idea or feature
type: request
labels: ["needs-triage"]
projects: ["doomemacs/2"]
body:
- type: markdown
  attributes:
    value: |
      Before you fill out this request, please make sure it hasn't already been
      requested by searching the project's source code **and** our issue
      tracker.
- type: textarea
  attributes:
    label: Describe your request
    placeholder: |
      I'd like X to be able to Y, without doing Z.
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      **Thank you for taking the time to fill out a feature request!**
